<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1xxuNhY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1xxuNhY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1xxuNhY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1xxuNhY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1xxuNhY\App_KernelDevDebugContainer([
    'container.build_hash' => '1xxuNhY',
    'container.build_id' => 'b7a1d499',
    'container.build_time' => 1759152994,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container1xxuNhY');
