<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUx6FTSZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUx6FTSZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUx6FTSZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUx6FTSZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUx6FTSZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ux6FTSZ',
    'container.build_id' => '9c512008',
    'container.build_time' => 1759155768,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUx6FTSZ');
