<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNN4WOAd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNN4WOAd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNN4WOAd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNN4WOAd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNN4WOAd\App_KernelDevDebugContainer([
    'container.build_hash' => 'NN4WOAd',
    'container.build_id' => 'c61e10de',
    'container.build_time' => 1759155600,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNN4WOAd');
